[package]
name = "cli"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "kythera"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
log = "0.4.17"
kythera-lib = { version = "0.1.0", path = "../lib" }
walkdir = "2.3.3"
wat = "1.0.61"

[dev-dependencies]
tempfile = "3.4.0"
